[package]
name = "mccm-assembler"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
lalrpop-util = { version = "0.22.1", features = ["lexer", "unicode"] }
clap = { version = "4.5.37", features = ["derive"] }
bitfield = "0.19.0"
either_n = "0.2.0"
